### PR TITLE
Reinstate and rework CI

### PR DESCRIPTION
**Pull request by madig**

### CODE REVIEW

**Comment by madig** [comment]
@simoncozens do you manually upload the generated wheels to PyPI?

**Comment by simoncozens** [comment]
Currently, yes.

**Comment by madig** [comment]
Ah, ok. The Linux wheels seem to be made twice. I think I can merge the manylinux job over and replace the linux-latest one?

**Comment by madig** [comment]
Ok, this seems to do the right thing now. Will try to do deploy in a separate PR.

**Pull request merged**
